name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
     tag:
       description: 'Tag for Docker image'
       required: false

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        
    - name: Build and push Docker image while workflow run automatically
      if: github.event_name != 'workflow_dispatch'
      uses: docker/build-push-action@v5.1.0
      with:
          file: multistage.Dockerfile
          push: true
          tags: petclinicAK:${{ github.sha }}

    - name: Build and push Docker image while workflow run manually
      if: github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v5.1.0
      with:
          file: multistage.Dockerfile
          push: true
          tags: petclinicAK:${{ github.event.inputs.tag }}
